INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Neighborhood Cleanup", "Environment", 400, "5/1/19", "6/01/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Dog Rescue Picnic", "Animals", 500, "5/1/19", "6/01/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Food Drive", "Children", 125, "5/1/19", "6/01/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Meals on Wheels", "Homeless", 75, "5/1/19", "6/01/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Nursing Home Reading", "Seniors", 100, "5/1/19", "6/01/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Victim Healing", "Domestic Violence", 65, "6/01/19", "7/01/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Wig Making", "Cancer Survivors", 1000, "6/01/19", "7/01/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Service Dog Class", "Blind", 500, "6/01/19", "7/01/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Musical Instruments", "Developmental Disabilities", 315, "6/01/19", "7/01/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("PTSD Counseling", "Military", 80, "6/01/19", "7/01/19");


INSERT INTO users (name, age) VALUES ("Bill Billins", 27);
INSERT INTO users (name, age) VALUES ("Ronald Ronalds", 29);
INSERT INTO users (name, age) VALUES ("David Davids", 34);
INSERT INTO users (name, age) VALUES ("Abby Abbies", 64);
INSERT INTO users (name, age) VALUES ("Tim Tims", 45);
INSERT INTO users (name, age) VALUES ("James Jameses", 67);
INSERT INTO users (name, age) VALUES ("Natasha Tashas", 42);
INSERT INTO users (name, age) VALUES ("Arnold Arnolds", 49);
INSERT INTO users (name, age) VALUES ("Chris Chrises", 31);
INSERT INTO users (name, age) VALUES ("Barry Barrys", 81);
INSERT INTO users (name, age) VALUES ("Brett Bretts", 72);
INSERT INTO users (name, age) VALUES ("Karen Karens", 64);
INSERT INTO users (name, age) VALUES ("Bob Bobs", 87);
INSERT INTO users (name, age) VALUES ("Michael Michaels", 21);
INSERT INTO users (name, age) VALUES ("Tito Titos", 32);
INSERT INTO users (name, age) VALUES ("Dylan Dylans", 24);
INSERT INTO users (name, age) VALUES ("Pat Pats", 43);
INSERT INTO users (name, age) VALUES ("Sammy Sams", 44);
INSERT INTO users (name, age) VALUES ("Brenda Brendas", 19);
INSERT INTO users (name, age) VALUES ("Tom Toms", 29);

INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 1, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 2, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 2, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 5, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 7, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 7, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 8, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 8, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 11, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 12, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 13, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 14, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 15, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 16, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 17, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 18, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 19, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 20, 1);
